### ISSUE TITLE
The project can't run on my localhost

### ISSUE THREAD

**Issue by Sunrise1970** [ocalvet/reactToDoList#1]
This is npm error message.I'm a beginner on react.so.please bear with me.

I don't know why warning me can't find webpack module,although I already' npm install' the package.json info.

and someone say,this project package.json don't config start script,so my 'npm start' get wrong.

_[root@localhost reactToDoList]# npm start

> react_todo@1.0.0 start /var/www/react-to-do-list/reactToDoList
> node server.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/var/www/react-to-do-list/reactToDoList/server.js:1:77)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! react_todo@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_todo@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react_todo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react_todo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react_todo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/react-to-do-list/reactToDoList/npm-debug.log_

**Comment by ocalvet** [comment]
Can you try running `$ npm install -g webpack webpack-dev-server` and then run `$ npm start` again?
